dist: trusty
sudo: required
language: python
python:
- '3.6'
services:
- docker
script:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
- docker pull akariv/google-chrome-in-a-box || true
- "./build.sh"
env:
  global:
  - secure: NuhH6uDQrcXPaKDIITjSzNpyHudwjmp0335S6whV65TQRZRSGrNuczLpdifdzpVQBMZTJaXDRiFGmgBX/ssPLIePZwOnP6WJu6p+RaXJSO/gLmhdG+cERR/jlrAY3jBopgkHW+ZAgcxn4PxaH2jzefZr1jjQbA2h3c0L7vvNsHlCKZB3Hi3FEgoSXp6KDaBz4i9ltttRMBgfgR8f/6ESNycDdFTruWKSX8XXQnqFq2f4tqY6OlZTkvJLbxWGlfgTqiIM8peSXUMWrCS8/uBEHGX6UwKxv9hHV/DjRde6CgNeWXVQgHa1Gxx23FJlStgD0B3BcyOa4T5VVNzxjYWoghRQN3OEOCeYmXN1oGMVskAUWhAao8cTdP9SgcuRJ1YRuh/mrd0N2R+jmQJnO/5CUhC6G5//1jR3Hb63Zo9cXD/WZwpeqiPW/J5H0goSP1CAmY8z2BZYxZzQH/kGgj6QH611JySa3Fu65mEOeDTLSVsTsTircg8DzfgYIKiBATeQ5vQq5SpRU5ib4FnKkcP9VgbQVS6ixys0eBUUrlQuBufrsiGI+wHiIzgW0ELh1yWz4YVJLBjICSxM3RUiZ5hcdBcE49eVqMY3fIvhHynfQLxmn5C1vQEQejoonxpIK3xMwN/fvpXLKCs2o3MQSARSK/pLuWp0G0dCUqdVMkNWs5I=
  - secure: wqgyqxZ6/fKJOOZBHO+bpTQfRFWkVO1ScVt2MH66ufQRvB55sZ7mjmt1WoN8EvQ/TMlqtB5bTK5x5Vcvau/tNXLPcFwcNx+uPwSMB5CwfiIcjPvez9aDpT7FrQJ0VpjcM/c6znQOHpUdlfAk+CNH2FZ9+VSU2IaQaMWY5OPBNXtOVjg1ZUhndQRce7GFjQJA3Q3pLbbW4BXE2Mk/Q21XIfPyp1q5INIoBuLmijz4VoVQYQV86Hwi52xK7BG++XP4DN24IqzCdizuETkWqKEBn3NbhTOBAcQ2lzHjwOUi2MEpsD2oYDt1xF+lkp/B+0YFh4FL9GdqWRA9dUFIidUq5RjdSUwpNUjdHye2Y3ttCFnC8pMxMJ6me4hWgRI4Kbu0bxCkyj3rD3U8oHejgUIoti/8xKog07FaFjPqzYXX2g9wO0LaVudoFE3kAvGaR/a3CSwXxUnPPojUwVJ0eQFc2K8Ezr/hsvYhPBE3qc+mSx0tqyJH8yET3tVSyNI3ZRVmSb6FybMA6akJMnSJf9Paehrhopurq2h+M9C8xw/bCg076QOlV6h3XhXGt4pXmrojlV1+tJi5UF9ySFImEi4DwN7u+s76gELZK8YZauy6D6fuao4pVtFcGP/ErucdvALlbrZO2kujUSBer14+peVirg7Q8sXWRDPwtEkAm2ejeM8=
